require("dotenv").config()
require("fs")
module.exports = {
  development: {
    // username: "jejakrem_marketplace",
    // password: "BangEpp070asq!",
    // database: "jejakrem_marketplace",
    // host: "119.82.243.98",
    // port: "3306",
    username: "muhammadisa",
    password: "muhammadisa",
    database: "marketplace",
    host: "172.19.57.178",
    port: "3307",
    // username: process.env.DB_USERNAME,
    // password: process.env.DB_PASSWORD,
    // database: process.env.DB_DBNAME,
    // host: process.env.DB_HOST,
    // port: process.env.DB_PORT,
    dialect: "mysql",
    timezone: "+07:00", // for writing to database
  },
  test: {
    // username: "root",
    // password: "",
    // database: "marketplace",
    // host: "127.0.0.1",
    username: process.env.DB_USERNAME,
    password: process.env.DB_PASSWORD,
    database: process.env.DB_DBNAME,
    host: process.env.DB_HOST,
    dialect: "mysql",
    timezone: "+07:00",
  },
  test: {
    // username: "root",
    // password: "",
    // database: "marketplace",
    // host: "127.0.0.1",
    // dialect: "mysql",
    username: process.env.DB_USERNAME,
    password: process.env.DB_PASSWORD,
    database: process.env.DB_DBNAME,
    host: process.env.DB_HOST,
    port: process.env.DB_PORT,
    dialect: "mysql",
    timezone: "+07:00",
  },
  production: {
    username: process.env.DB_USERNAME,
    password: process.env.DB_PASSWORD,
    database: process.env.DB_DBNAME,
    host: process.env.DB_HOST,
    // "username": 'root',
    // "password": null,
    // "database": 'marketplace',
    // "host": '127.0.0.1',
    dialect: "mysql",
  },
}
